Changed case of spelling
nextcloud/backup pull request #75
Opened 2021-11-16 17:15 UTC by rakekniven

Reported at Transifex.

Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

2021-11-18 21:58 UTC, ArtificialOwl approved these changes

2021-11-18 22:03 UTC, ArtificialOwl commented
is it really needed to switch `\'` to `\"` in the vue files ? it seems to f*ck eslint

2021-11-19 08:27 UTC, rakekniven commented
Yes, all messages in the entire NC project are aligned to use " instead of ' .

2021-11-19 08:32 UTC, ArtificialOwl commented
@artonge any idea why this break eslint ?

2021-11-19 09:18 UTC, Valdnet requested changes

2021-11-19 09:27 UTC, Valdnet requested changes

2021-11-19 09:27 UTC, Valdnet commented on appinfo/info.xml
>  	  - Backup the instance, its apps, your data and your database,
```suggestion
      - Backup the instance, its apps, your data and your database,
```

2021-11-19 11:24 UTC, artonge approved these changes

2021-11-19 12:05 UTC, ArtificialOwl commented
@rakekniven do you agreee with @artonge's changes ?
https://github.com/nextcloud/backup/pull/75/commits/4a36e5f5d89944441a64526c49ec782b192edc38

2021-11-19 12:20 UTC, rakekniven commented
Yes, that is fine with me.

2021-11-19 12:36 UTC, merged