Correct punctuation
nextcloud/backup pull request #85
Opened 2021-11-20 14:17 UTC by Valdnet

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

2021-11-20 18:04 UTC, ArtificialOwl approved these changes

2021-11-20 18:04 UTC, ArtificialOwl commented
i will do some work on the documentation next week

2021-11-21 16:33 UTC, rakekniven requested changes

2021-11-21 16:33 UTC, rakekniven commented on README.md
> +- Retreiving data from local
Retreiving -> Retrieving

2021-11-21 16:50 UTC, Valdnet commented on README.md
> +- Retreiving data from local
Done 😉.

2021-11-21 16:52 UTC, rakekniven approved these changes

2021-11-21 16:52 UTC, merged